### ISSUE TITLE
Remove language selection from Game settings

### ISSUE THREAD

**Issue by varnholt** [varnholt/platformer#1]

**Comment by varnholt** [comment]
I can't find them.
Please just attach them here or replace them via github.

**Comment by dstar64** [comment]
[gamefolder]\Graphics\UI\menus\

[menus.zip](https://github.com/varnholt/platformer/files/2989081/menus.zip)

**Comment by varnholt** [comment]
The uploaded PSDs are missing required layers
References: 
- menuscreenvideo.cpp
- menuscreengame.cpp
