### ISSUE TITLE
New Camera System

### ISSUE THREAD

**Issue by dstar64** [varnholt/platformer#38]
A nice idea of how our camera system should work

[https://www.gamasutra.com/blogs/JochenHeizmann/20171127/310386/Camera_Logic_in_a_2D_Platformer.php?fbclid=IwAR2xyfnIOr2QXqxeWwhQoXr6a89SxVUdaW8DozXLqLJ_Esq82leMVLZC-cc](url)

**Comment by varnholt** [comment]
## Camera system

### Camera X position
- dist = distance between old camera x position and the current x player position
- dist /= 32
- offset = min(dist, max_camera_speed)
- have a focus zone which is a rectangle around the player; if the player walks out of the focus zone, apply the offset
- that rectangle is moved further to the left if the player looks to the right and vice versa.
- if the player accelerates in a direction that rectangle is moved even further into the opposite direction.

### Camera Y position
- dist = distance between old camera y position and the current player y position
- dist /= 16
- the camera is only moved when the player touches the ground
- have two 'panic lines' at the top and bottom of the screen; if the player falls through those lines, move the camera
